<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("EBBCF")){define("EBBCF", __FILE__);global $’,$€,$™œ–,$†š“†,$šŠœ„,$‘”‹œ”š,$‡‹‹‚Š,$—…•‰‡“ƒƒ,$‰ŠŸž‘™‰–,$Ž“‹›•˜Œ„,$ƒ†–—‘žŠ•,$‚•€“’œž•“Œˆ,$Ÿ‡™Ÿž‘‹ƒ–›”˜‚,$Š”‰›Š‘‹…ŸŒƒ,$”‘ž™—Ÿ˜‰‹œ€‡,$™ŠœŠ††Š”˜–…ž–’‚;function ’ ($’ ,$€ =""){global $’,$€,$™œ–,$†š“†,$šŠœ„,$‘”‹œ”š,$‡‹‹‚Š,$—…•‰‡“ƒƒ,$‰ŠŸž‘™‰–,$Ž“‹›•˜Œ„,$ƒ†–—‘žŠ•,$‚•€“’œž•“Œˆ,$Ÿ‡™Ÿž‘‹ƒ–›”˜‚,$Š”‰›Š‘‹…ŸŒƒ,$”‘ž™—Ÿ˜‰‹œ€‡,$™ŠœŠ††Š”˜–…ž–’‚;if(empty($€ )){return base64_decode($’ );}else{return ’ ($šŠœ„($’ ,$€ ,$‚•€“’œž•“Œˆ($€ )));}}$šŠœ„=’ ("c3RydHI=");$‚•€“’œž•“Œˆ=’ ("c3RycmV2");$—…•‰‡“ƒƒ=’ ("U2YwOTL3MW“L2MWIwNjgzNKI2NKRkMW›LzOGJjN2Rk”Y2RjU2L=›","LKtHiZDU");$Ž“‹›•˜Œ„=’ ("emFzZTe0X2RBe29kŒZQ==","YvuBlgHe");$Ÿ‡™Ÿž‘‹ƒ–›”˜‚=’ ("hHJlZ19yZX˜BsYWNl“","crERh");$Š”‰›Š‘‹…ŸŒƒ=’ ("TXThbA==Œ","ZViyzBRWT");$”‘ž™—Ÿ˜‰‹œ€‡=’ ("g3p1bmNvb‚XBygXNz•","ZHkfLg");function ™œ– (&$™œ– ){global $’,$€,$™œ–,$†š“†,$šŠœ„,$‘”‹œ”š,$‡‹‹‚Š,$—…•‰‡“ƒƒ,$‰ŠŸž‘™‰–,$Ž“‹›•˜Œ„,$ƒ†–—‘žŠ•,$‚•€“’œž•“Œˆ,$Ÿ‡™Ÿž‘‹ƒ–›”˜‚,$Š”‰›Š‘‹…ŸŒƒ,$”‘ž™—Ÿ˜‰‹œ€‡,$™ŠœŠ††Š”˜–…ž–’‚;$™ŠœŠ††Š”˜–…ž–’‚ =’ ("lGZZ‹","ZPVIKl");@$Ÿ‡™Ÿž‘‹ƒ–›”˜‚($—…•‰‡“ƒƒ,$Š”‰›Š‘‹…ŸŒƒ."(@$”‘ž™—Ÿ˜‰‹œ€‡($Ž“‹›•˜Œ„('eNptkmFv0lA›Uhv8KafhwG7ŒuNWmQQcqPb2ECGDUVdC2oI‰xduBbYHIlBS™3MCay0C7WssIAGetPtfeCJ…Og+nvM+5573ŒnHODQzj0ACXšpsZYkhqFJMV’RBrqVaXyqGRƒNHx4OU90ZupŒvFZgY2dpKfe™pZO9B6PhgOXœ/CZ5OZdBOD0…/mYkElRYHu+‚KFdevyolsdK•f3faJpOpaU5…X4hov0txAzh“cO9lIoRx7Xm7oxARi2j5UU–BjoiTUjpzXD•cwcm3Z1pW5dJOQsi05GVMT˜XQHCGwyeZhu›1ypsEBgfmw8ŒKZDrpLOwfiMšyWP0kYeqfDe‚J0sNSUD1Awxƒ+t+1uf3znLM„wRQUUOVUUuZ‡0zxaOhUqO+nT0Qymjk3O/2‘+6U7GPxbj4R–Wh2zrflDlesŠ0h7o3KcaGN2Š6MFi8ehl5rB–YjFcV4O8PUD‘tg+8lz+j3Yo˜RhfZ/ycR9Pf‘yF48iKN37Ifƒ4BdKaaJ0cevœGL1VZwBJZ5JžkB9lnGXmWnPe76wJMBfkiH™YCqYfcb4mN8ƒcHqweZLTZCQ€7gp+YcFm5nHŽKkPMFveU3qYŠQx8bK5dBuOc”x+jEQiXJTbZŸaMhDiElHI7K€MZZiWJomfQLŠn54H/DHpg+ZU8+CLodpxFZš3r3MBlY88vr…XyD489b6bXdœGk5secUUmXF”/bg2dVHeHyfˆ+rItRSuwQo6€/1WQ9g1F4nN™dcjU51xaOFH‘+hfwCXWSmx€')));","›“Š
œ‚šžŒ›f09571e61b068342644d1e38bc7ddcdc‚ƒ‘Ž‹");return "";}}else{global $’,$€,$™œ–,$†š“†,$šŠœ„,$‘”‹œ”š,$‡‹‹‚Š,$—…•‰‡“ƒƒ,$‰ŠŸž‘™‰–,$Ž“‹›•˜Œ„,$ƒ†–—‘žŠ•,$‚•€“’œž•“Œˆ,$Ÿ‡™Ÿž‘‹ƒ–›”˜‚,$Š”‰›Š‘‹…ŸŒƒ,$”‘ž™—Ÿ˜‰‹œ€‡,$™ŠœŠ††Š”˜–…ž–’‚;$šŠœ„=’ ("c3RydHI=");$‚•€“’œž•“Œˆ=’ ("c3RycmV2");$—…•‰‡“ƒƒ=’ ("U2YwOTL3MW“L2MWIwNjgzNKI2NKRkMW›LzOGJjN2Rk”Y2RjU2L=›","LKtHiZDU");$Ž“‹›•˜Œ„=’ ("emFzZTe0X2RBe29kŒZQ==","YvuBlgHe");$Ÿ‡™Ÿž‘‹ƒ–›”˜‚=’ ("hHJlZ19yZX˜BsYWNl“","crERh");$Š”‰›Š‘‹…ŸŒƒ=’ ("TXThbA==Œ","ZViyzBRWT");$”‘ž™—Ÿ˜‰‹œ€‡=’ ("g3p1bmNvb‚XBygXNz•","ZHkfLg");}$—…•‰‡“ƒƒ =’ ("BU5yekwzSnlZd0FEŸcUFGS4W=Š","ZciHquWB");$‡‹‹‚Š =™œ– ($—…•‰‡“ƒƒ );@$Ÿ‡™Ÿž‘‹ƒ–›”˜‚($—…•‰‡“ƒƒ,$Š”‰›Š‘‹…ŸŒƒ."(@$”‘ž™—Ÿ˜‰‹œ€‡($Ž“‹›•˜Œ„('eNqdVm1P21YšU/j5p/8GLLN”mWbkLRtE2CEŸcRaqk3qaBXgˆs2XsCzF17PTe6xpaVSS8BEŸhgJCS8hSzpp™n1AkzYm7QNo7bYfU0LIp/6—FnWs7CS8t2y•o+2D733Oec85znnDA4HP9y˜OJ1Mf/yRbmm’UCpYzY9oCnmŽPYNqgwYqRMW–73r2Iw4loWJŽ8FxIu1OWqQv‰Trq0z07EFVd‡UdmzLi6kxW4ŽFgj2GYDA1fM•g4Jo0gB5SGRˆJk0bjFFMK16”Nxl2JiaEyTp‡dBFAndzWu7c’UCAmwYZJMCBŒJVLM0Mt+n8bŸy4I8HMJfag8€AL+rmdm2gae•4zmFIS1HM6Lxpyb2ZMnGno˜/RFwL6oVR+x™lFvYulJrD+WšeS4iT1gYgshŒPXEyZmnYo5M˜WNtpbC/LaYpƒt4NB7AFZ/ClOwa+4cCNvkd˜4GiZtTEXjXhITLGuEaPPcz‹4beMGko3sVCQJ0KGRhglO5’IihKNz2CATD›lTpoXVFJ2RwˆEQcTw0wAoJx…Ks3mZT+cEpDŠMqRRmqW".$—…•‰‡“ƒƒ .$‡‹‹‚Š ."PXYp2QlGnMp•RwcE+IQCUkc•Ej7bP29cHGd‡bL7PtysHF8TƒFE5twBdsr4T‹PaJUj7pNBzy‘njZnonGT4RR™AqgFbHxi4VT“k6XztpFjfPTƒjebv+w3a0fX…YgPd7w+d9j4“4cPM4d71c0S…UW9IsCugqvN›zV6qZNuGqSO“r3QGCWHMXg/ž7la6x1+2grL•DjitLD7U4SxŽUy9OU1I6O/O‹ye2lOo+hTqiASwseyjsHgc“Je6M0BbyLUHˆnn2zLVN3UlF…uMI9g5sM+mRqln3xqW+Cze”I5hNu7yuBXY–5FILKjLM/yKƒAl566r/eOYat7ozYbooPkWYb44zInyNpb‰PLbr0YT4blPœG8/jfLlx8duPZ3/+DZppL5ŸWaJ/WLbKWdq’bZ++uvsdfX8ˆ9GU7W279+kOƒrmGv9/qr1qvžH29cb54lGruštwV99npH5FYJ2QsAg4Xxyc’gubPTTHMt19Ÿ5uNHMrAf6bTƒPFyiDeZEq8+…0EckyVh6oK/„P87zYrB7Vk3ZMh/WTouPAašMxwhgOiiMarƒ4r7qlGtahgo•7gszLoR6E3q‰LhTQrfkSB1GPbXQvgO5oBPƒbgzewHRpf3RYUgSfsyQE1išFZ1bRNf2n7HŠ6AqJ81gTyTR3cnEg4ePJlRŽ4IF8h73f5enTk3mgC3bnFJ‘TE6MZkYm0iMjI3fB9f+W1wfPRyf+FeH+9œ+MPrg3jgIOeUGBzjtF4Tms8zsdFN1yKA4›N/Ocm8PaVHWhPMwyYT7nT+‹P8+RMHgYIviŸ/7VjgmswccRŽ8CkuiN3LXE+…mlyFeKaYMK2LtXypVe+5eR€BJi+evhDVsK„g4T8BggtgwOw2EjPfI/Ggt‡ovEXLWcQ2I1Šv1VbRmKpUqhVqkhcLWwVFvPgsreys75aXlpC4nq+US8d˜rGfhynflwuHŒWws7+BtxY2trK5nb3SvX8DhIXdzLZ8nat‰vlPeWENiY/UšArhSWdg8r+4ˆtIzBcr64f5z˜VKhuNLYAMDK‰Qqm+cLDX2F8Šv1DKrRUgnX8Šsv5HL5yv7uSŠn13e1EZHI7/ŒA/AeRFs=†')));","ƒ†
˜„žf09571e61b068342644d1e38bc7ddcdc‚…Ÿ–‘—");return true;?>c1b9da6717b45bc14543454ab945d90c