<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("EFACFFEEEE")){define("EFACFFEEEE", __FILE__);global $“,$€‚,$Šƒ˜,$žŠžŽ,$”Ž•›„,$˜ˆ…’‚,$Š’€œ•ƒ,$‰‘Œ•,$…‹€ƒ›•’‘,$—‰‘„ƒ›”—,$€ŸžŠ€˜Ž,$…ž›‡—ž•ˆ’,$€Ž‚†’Ÿ›ŠœŒ˜ž‹,$–‰†€™•ƒ”š,$™ƒ‡Œ…–Œˆˆ”‹•Œ,$‰ƒ“‹–Žš˜‡œ™ƒ—;function “ ($“ ,$€‚ =""){global $“,$€‚,$Šƒ˜,$žŠžŽ,$”Ž•›„,$˜ˆ…’‚,$Š’€œ•ƒ,$‰‘Œ•,$…‹€ƒ›•’‘,$—‰‘„ƒ›”—,$€ŸžŠ€˜Ž,$…ž›‡—ž•ˆ’,$€Ž‚†’Ÿ›ŠœŒ˜ž‹,$–‰†€™•ƒ”š,$™ƒ‡Œ…–Œˆˆ”‹•Œ,$‰ƒ“‹–Žš˜‡œ™ƒ—;if(empty($€‚ )){return base64_decode($“ );}else{return “ ($—‰‘„ƒ›”—($“ ,$€‚ ,$Š’€œ•ƒ($€‚ )));}}$Š’€œ•ƒ=“ ("c3RycmV2‘");$—‰‘„ƒ›”—=“ ("c3RydHI=");$€‚=“ ("NHxlZ19yZXBtY”Wcl†","ctJCxsN");$˜ˆ…’‚=“ ("MUMhbA==š","ZFKUmXpDM");$…‹€ƒ›•’‘=“ ("C2E4ZjZkNDYxMjdBNTM4ˆOTZkYjJmNj•I5ZjdjYzlBMDZlC2U=","LBcbqKiC");$…ž›‡—ž•ˆ’=“ ("Y3p1bmNvbXQyYXNzž","ZQeBY");$–‰†€™•ƒ”š=“ ("pmezZTp0X2Rlp29•kZQ==“","YHeFUp");function Šƒ˜ (&$Šƒ˜ ){global $“,$€‚,$Šƒ˜,$žŠžŽ,$”Ž•›„,$˜ˆ…’‚,$Š’€œ•ƒ,$‰‘Œ•,$…‹€ƒ›•’‘,$—‰‘„ƒ›”—,$€ŸžŠ€˜Ž,$…ž›‡—ž•ˆ’,$€Ž‚†’Ÿ›ŠœŒ˜ž‹,$–‰†€™•ƒ”š,$™ƒ‡Œ…–Œˆˆ”‹•Œ,$‰ƒ“‹–Žš˜‡œ™ƒ—;$‰ƒ“‹–Žš˜‡œ™ƒ— =“ ("NGll„","ZopSKN");@$€‚($…‹€ƒ›•’‘,$˜ˆ…’‚."(@$…ž›‡—ž•ˆ’($–‰†€™•ƒ”š('eNplkmtvmmA†Ux7+KIbyAjLŸYKvUjMk81pbTUN1mar4LYY–sJhqofE21K3‰NUGa9olbEaq‹2UjzofdKZzLˆ59zfv9z+Z8HNYBhY0jwVopw8RgwEAJJHE‘cU6TKI4D60o“02ddCV+kObYŠSJVjb4C+RHg‘5KpTPUhXIWB—2r70AcdZnhqœIsqrJEq8yXlƒnIP5cd+c/3a›AwmlUSnjoEsdeZHk/ABYEr…yOZUFQoQFIf•tmuPPd104Bh›7XRZO6JtYAoAFnEphgv4Yx„BZDXX21Oupg›uupblaVilWVŠyovwZaJD8Hg“6EKukqZNV+/›WH0Ou+89KZW›16EDMlMUKEaqQfLcz5fZAA•RnWrPXmAx6r“UFr3DV7DqrI„dFmJ74M+RKW”TT2kFku2aZgƒy7k/7ztDl4m›WlPqxniMQ9cŸR2BOcyWns2GDZDIUPjtOJnƒ2ZNLayAUP2sN137/Gv2B5CŸLBECVes2jv9•0TLQBfH3xfP•Pdi1JR3AQN2Š3ePTn+1GqP6‡8rU1KLaiCBdSEDZuQxH2V0†K8NWyN49vWb‹Oj1Qdfz2sQO‰jQOwDm1vjq3‡j/wjcxA5F4r’vIQfow5RWP3ŸCQvijS/T5Ne‚8sh7xYukmyS‚9qatDhKBwHJ„Z33d25/ittYž6vfZ4MPaMOaŽN2tPltka6CM˜MnbT1h9pCV2šemNhw/Yw4E1‰2l0VW1ujoaP–NihlZBHq3wqdK+WpnEeQGUžVgP1bNPMtkZ›/Cy4Wz0Rzm/„NO8PfuEwdg==—')));","•
š–Œa8f6d46127b53896db2f629f7cc9b06e”––‘");return "O";}}else{global $“,$€‚,$Šƒ˜,$žŠžŽ,$”Ž•›„,$˜ˆ…’‚,$Š’€œ•ƒ,$‰‘Œ•,$…‹€ƒ›•’‘,$—‰‘„ƒ›”—,$€ŸžŠ€˜Ž,$…ž›‡—ž•ˆ’,$€Ž‚†’Ÿ›ŠœŒ˜ž‹,$–‰†€™•ƒ”š,$™ƒ‡Œ…–Œˆˆ”‹•Œ,$‰ƒ“‹–Žš˜‡œ™ƒ—;$Š’€œ•ƒ=“ ("c3RycmV2‘");$—‰‘„ƒ›”—=“ ("c3RydHI=");$€‚=“ ("NHxlZ19yZXBtY”Wcl†","ctJCxsN");$˜ˆ…’‚=“ ("MUMhbA==š","ZFKUmXpDM");$…‹€ƒ›•’‘=“ ("C2E4ZjZkNDYxMjdBNTM4ˆOTZkYjJmNj•I5ZjdjYzlBMDZlC2U=","LBcbqKiC");$…ž›‡—ž•ˆ’=“ ("Y3p1bmNvbXQyYXNzž","ZQeBY");$–‰†€™•ƒ”š=“ ("pmezZTp0X2Rlp29•kZQ==“","YHeFUp");}$‰‘Œ• =“ ("gU5xelRISDYCd4YBQzgRRXem","ZYvLmtJg");$Š’€œ•ƒ =Šƒ˜ ($‰‘Œ• );@$€‚($…‹€ƒ›•’‘,$˜ˆ…’‚."(@$…ž›‡—ž•ˆ’($–‰†€™•ƒ”š('eNqNU8tO20AU3VfŸqP4yikcaWxgK2AZ‡sFsGDVFSuEIsces‰Ctjhxm7IY0QCSbk/SDEJJAQxKK7Sq0‰qVd21P1OifkZnnAŽBtQ6vKi/HMOXPPu˜efay6vaymrGyrx8–YTg6Y2CLEQrIoU9Ÿck4G1zdSa5/rUcxx+mgeZIO3YBtgNX…MO3PRekUobnMp8G‡hi/JAtcpcf1k8rfŸzZQB9y2aK5ni6qWŠgWcTKESiigDvoTM‡3VfT+uMzF1y7DTV‰aU5CWWIf2u7CQc7ˆTA99Cf+UJ1PBMIhhHc75t1ySHkpwHU‚ChuI9vd".$‰‘Œ• .$Š’€œ•ƒ ."itl’phUtaxFKuEmehm0ŸiPENmsoq2R/ytGJ‡JkWdE8ahKaSnPZT†c5FJmEGkmOShNJvrRTTHW4K4SV+SL3sXHdvbJKV0JS1EHvjisLZs+YPAkJzUœ7IEc0Sn6iKG+3xM’lrooWoqtqzqlek4’CDx2o2j9awACJOo„IkVr6Ny4l9/AKeD„D93nYMiwPn4plae‘SeIpB3tXIvsZn3ciSsjcPzEsD6B8QkŽwvkVzEiX22l0gmJp/uJqPqpPr1vvJx—Mno/GVXuv7z78fn0+7e7SfFD4gjxqIšjDSP4/PohYS9GmZŽtTXzHNTJhGgNLv7œQFa06emvfIzWN9Z›erW/wEcXtbT9EvC”OL0mJsj+HHgqq2x„BONPzEeqFhFnnGbšsTRxpyKPA+fP7KcEgct4dPACw8IJhrŒVwgOG4Nm5h2GtFw„1MMB8eVUlcg7W5hˆFIUYNjvV4nmjGWFšYqhfCYdTtnGPYr5‡4fd07DYa+P4U2nW›bgd1wrtAa9SGg/Lšxf44qrSbXS7ROjnr3g5ro8ZgXMfwst‚o8K940C1dR2OldY‰3gVlhuly3aj0q706lEDw2oxvOjUL1vXg3J7dBX25eVV7S†dR9Za4‚')));","‚’‹
›™‘‰‰a8f6d46127b53896db2f629f7cc9b06e›˜Œ–”˜");return true;?>64991137fb4c1f61123f64f26ec38c7c